### ISSUE TITLE
Create used ESLint rules list

### ISSUE THREAD

**Issue by ryym** [interfirm/eslint-config-interfirm#2]
今の状態だと、結局どんなルールが有効になっているのかがよくわからないので、使われているルールの一覧を作る。また、そのルールに関する説明も必要。これはESLintのWebサイトへのリンクで良さそう (e.g. [no-console](http://eslint.org/docs/rules/no-console))。

**Comment by ryym** [comment]
@riseshia ルールの一覧を簡単に生成してみたのですが、どうですか？
ちゃんと書こうとすると大変ですけど、このくらいなら自動生成できるので楽です。
- https://github.com/interfirm/eslint-config-interfirm/tree/eslint-rules/rules

**Comment by riseshia** [comment]
設定のリストなので結構見通しが良くないな、と思うのですがどうですか？見慣れてないせいかな。。？

**Comment by ryym** [comment]
自分も見通しが良いとは思いませんけど .. 😓 
やはりルールの説明やコード例が欲しいですか？  [Airbnbの Coding Guide](https://github.com/airbnb/javascript)ならありますけど、こういうのを自分たちで作るのも大変ですよね。

**Comment by riseshia** [comment]
なしでもいいと思います！あったら、いいな、とは思いますが、今すぐ役にたくものではないので

**Comment by ryym** [comment]
了解です!
