### ISSUE TITLE
Migrate to ESLint v4

### ISSUE THREAD

**Issue by ryym** [interfirm/eslint-config-interfirm#57]
<http://eslint.org/docs/4.0.0/user-guide/migrating-to-4.0.0>

依存しているプラグインが対応するのを待つ必要がある。

**Comment by ybiquitous** [comment]
`eslint-config-airbnb` のこの issue 👇 が解決されれば、着手可能かも。
https://github.com/airbnb/javascript/issues/1447

**Comment by ybiquitous** [comment]
更新来ました〜

**Comment by ybiquitous** [comment]
Warnings:

```
can't resolve reference #/definitions/basicConfig from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
can't resolve reference #/definitions/basicConfigOrBoolean from id #
```

- https://github.com/airbnb/javascript/issues/1488
- https://github.com/yannickcr/eslint-plugin-react/pull/1292

The fixed version of `eslint-plugin-react` is not yet released 😞

**Comment by ybiquitous** [comment]
Fixed via #82

**Comment by ybiquitous** [comment]
@interfirm/dev 
ESLint v4 に対応しました！
各プロジェクトの `package.json` で `"eslint": "3"` と固定している場合は、バージョン 🆙 できますのでよろしくお願いします 🙇

**Comment by ryym** [comment]
@ybiquitous ありがとうございます 🎉
