### ISSUE TITLE
ルールの微調整

### ISSUE THREAD

**Issue by ryym** [interfirm/eslint-config-interfirm#6]
### [comma-dangle](http://eslint.org/docs/rules/comma-dangle)

今は`off`になっているが、人によって書き方がバラバラになってしまうので`always`か`never`どちらかに統一したい。

### [max-len](http://eslint.org/docs/rules/max-len)

hubotのプロジェクトだと最大文字数を超える文字列が結構ある。共通ルールとして、以下のように長くなりがちなコードをチェックの対象にするかどうかを統一できると楽。

- 文字列
- コメント
- URL
- 正規表現

### [no-plusplus](http://eslint.org/docs/rules/no-plusplus)

Forループの時だけOKにしたい ([option](http://eslint.org/docs/rules/no-plusplus#options))。

**Comment by ryym** [comment]
- common-dangle -> 最後にカンマを強制する。
- max-len -> 文字列をアリにするとルールとしてゆるすぎるので、文字列はinterfirm-hubotでだけOKにする。
- no-plusplus -> １つのプロジェクトで1箇所`--`を使っているだけなので、修正して引き続きエラーとする。

**Comment by sakahiro** [comment]
@ryym 上記のルールは全て適応できました。クローズしても大丈夫ですか？

**Comment by ryym** [comment]
@sakahiro ありがとうございます!
